"""Export service for generating PDF and DOCX files."""
import io
from datetime import datetime
from typing import Dict, Any
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import markdown
from reportlab.lib.utils import simpleSplit


class ExportService:
    """Service for exporting test plans to various formats."""
    
    def generate_pdf(
        self,
        content: str,
        jira_ticket_id: str,
        title: str
    ) -> bytes:
        """Generate PDF from markdown content."""
        buffer = io.BytesIO()
        
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        # Container for the 'Flowable' objects
        story = []
        
        # Styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        heading1_style = ParagraphStyle(
            'CustomH1',
            parent=styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=12
        )
        heading2_style = ParagraphStyle(
            'CustomH2',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#2563eb'),
            spaceAfter=10
        )
        heading3_style = ParagraphStyle(
            'CustomH3',
            parent=styles['Heading3'],
            fontSize=12,
            textColor=colors.HexColor('#3b82f6'),
            spaceAfter=8
        )
        body_style = styles['BodyText']
        body_style.fontSize = 11
        body_style.leading = 14
        
        # Title Page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("Test Plan", title_style))
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(f"JIRA Ticket: {jira_ticket_id}", heading2_style))
        story.append(Paragraph(title, heading2_style))
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", body_style))
        story.append(Paragraph("Generated by TestPlan Agent", body_style))
        story.append(PageBreak())
        
        # Table of Contents
        story.append(Paragraph("Table of Contents", heading1_style))
        story.append(Spacer(1, 0.3*inch))
        
        # Parse content and add sections
        lines = content.split('\n')
        toc_items = []
        current_section = None
        
        for line in lines:
            if line.startswith('# '):
                toc_items.append(('h1', line[2:].strip()))
            elif line.startswith('## '):
                toc_items.append(('h2', line[3:].strip()))
            elif line.startswith('### '):
                toc_items.append(('h3', line[4:].strip()))
        
        for level, text in toc_items:
            indent = "    " if level == 'h2' else "        " if level == 'h3' else ""
            story.append(Paragraph(f"{indent}{text}", body_style))
        
        story.append(PageBreak())
        
        # Content
        current_table_data = []
        in_table = False
        
        for line in lines:
            line = line.strip()
            if not line:
                if in_table and current_table_data:
                    # End table
                    table = Table(current_table_data)
                    table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, 0), 10),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                        ('GRID', (0, 0), (-1, -1), 1, colors.black),
                        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ]))
                    story.append(table)
                    story.append(Spacer(1, 0.1*inch))
                    current_table_data = []
                    in_table = False
                continue
            
            # Headers
            if line.startswith('# ') and not in_table:
                story.append(Paragraph(line[2:], heading1_style))
            elif line.startswith('## ') and not in_table:
                story.append(Paragraph(line[3:], heading2_style))
            elif line.startswith('### ') and not in_table:
                story.append(Paragraph(line[4:], heading3_style))
            
            # Table handling
            elif line.startswith('|') and not line.startswith('|--'):
                in_table = True
                cells = [cell.strip() for cell in line.split('|')[1:-1]]
                current_table_data.append(cells)
            
            # Bullet points
            elif line.startswith('- ') or line.startswith('* '):
                story.append(Paragraph(f"• {line[2:]}", body_style))
            elif line.startswith('  - ') or line.startswith('  * '):
                story.append(Paragraph(f"    ◦ {line[4:]}", body_style))
            
            # Numbered lists
            elif line[0].isdigit() and '. ' in line[:4]:
                story.append(Paragraph(line, body_style))
            
            # Regular text
            else:
                story.append(Paragraph(line, body_style))
        
        # Build PDF
        doc.build(story)
        
        pdf = buffer.getvalue()
        buffer.close()
        
        return pdf
    
    def generate_docx(
        self,
        content: str,
        jira_ticket_id: str,
        title: str
    ) -> bytes:
        """Generate DOCX from markdown content."""
        doc = Document()
        
        # Title Page
        title_para = doc.add_heading('Test Plan', 0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph()
        
        jira_para = doc.add_paragraph()
        jira_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        jira_run = jira_para.add_run(f'JIRA Ticket: {jira_ticket_id}')
        jira_run.font.size = Pt(14)
        jira_run.bold = True
        
        title_para2 = doc.add_paragraph()
        title_para2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para2.add_run(title)
        title_run.font.size = Pt(14)
        
        doc.add_paragraph()
        
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_run = date_para.add_run(f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        date_run.font.size = Pt(11)
        
        gen_para = doc.add_paragraph()
        gen_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        gen_run = gen_para.add_run('Generated by TestPlan Agent')
        gen_run.font.size = Pt(11)
        gen_run.italic = True
        
        # Page break
        doc.add_page_break()
        
        # Table of Contents
        doc.add_heading('Table of Contents', level=1)
        
        lines = content.split('\n')
        toc_items = []
        
        for line in lines:
            if line.startswith('# '):
                toc_items.append(('h1', line[2:].strip()))
            elif line.startswith('## '):
                toc_items.append(('h2', line[3:].strip()))
            elif line.startswith('### '):
                toc_items.append(('h3', line[4:].strip()))
        
        for level, text in toc_items:
            p = doc.add_paragraph()
            if level == 'h2':
                p.paragraph_format.left_indent = Inches(0.3)
            elif level == 'h3':
                p.paragraph_format.left_indent = Inches(0.6)
            p.add_run(text)
        
        doc.add_page_break()
        
        # Content
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            # Headers
            if line.startswith('# '):
                doc.add_heading(line[2:], level=1)
            elif line.startswith('## '):
                doc.add_heading(line[3:], level=2)
            elif line.startswith('### '):
                doc.add_heading(line[4:], level=3)
            
            # Table handling (simplified)
            elif line.startswith('|') and not line.startswith('|--'):
                cells = [cell.strip() for cell in line.split('|')[1:-1]]
                if cells:
                    table = doc.add_table(rows=1, cols=len(cells))
                    table.style = 'Light Grid Accent 1'
                    for i, cell_text in enumerate(cells):
                        table.rows[0].cells[i].text = cell_text
            
            # Bullet points
            elif line.startswith('- ') or line.startswith('* '):
                p = doc.add_paragraph(line[2:], style='List Bullet')
            elif line.startswith('  - ') or line.startswith('  * '):
                p = doc.add_paragraph(line[4:], style='List Bullet 2')
            
            # Numbered lists
            elif line[0].isdigit() and '. ' in line[:4]:
                p = doc.add_paragraph(line[line.find('. ')+2:], style='List Number')
            
            # Bold text
            elif line.startswith('**') and line.endswith('**'):
                p = doc.add_paragraph()
                run = p.add_run(line[2:-2])
                run.bold = True
            
            # Regular text
            else:
                doc.add_paragraph(line)
        
        # Save to buffer
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        
        return buffer.getvalue()


# Global export service instance
export_service = ExportService()
